### ISSUE TITLE
As an User I want to see pricing for Visa stock on NYSE 

### ISSUE THREAD

**Issue by valentinbadea** [iLiviu/road-to-fire#10]
The app asks for manual input price for Visa (NYSE:V)
![Screenshot_20200226_191302_com android chrome](https://user-images.githubusercontent.com/44651099/75369400-0b0a0480-58cc-11ea-9e81-e6a1702483a4.jpg)

**Comment by iLiviu** [comment]
The problem was with the quote service provider not accepting 1 character symbols and it has been fixed.
