### ISSUE TITLE
A stroage connector with Nextcloud?

### ISSUE THREAD

**Issue by jeremyfritzen** [iLiviu/road-to-fire#21]
I'm nw to Road To Fire but this seems fantastic!
I would like to suggest an improvement: since Nextcloud is well-adopted by opensource community, it would be really nice if Road To Fire was able to integrate with Nextcloud as a backend storage.

What do you think?

**Comment by iLiviu** [comment]
Unfortunately i don't have any plans on adding extra backend storages. RemoteStorage protocol has some open source server implementations so you can host your own server if you want to do so for privacy reasons.
