### ISSUE TITLE
Wrong BTC price updates

### ISSUE THREAD

**Issue by pabloegpf1** [iLiviu/road-to-fire#22]
Hi!

I have set up my account with EUR as base currency.

When I refresh the asset prices, the BTC value is fetched in USD but appears in EUR without conversion. This happens with both Binance and Coinbase.

For example, right now it shows 59.748€ per BTC (it should be 50.113€).

**Comment by iLiviu** [comment]
Base currency and asset currency are 2 different things. There is no conversion done to the price received for the asset, as you need to enter the symbol for the currency pair you actually bought. For example if you bought with EUR, then the ticker (symbol) would be BTCEUR (works on Coinbase only for now, not Binance).

**Comment by pabloegpf1** [comment]
Changing the exchange to Coinbase works as expected. Thanks!
