### ISSUE TITLE
Have a way to close the "connect to save" popup

### ISSUE THREAD

**Issue by strainu** [iLiviu/road-to-fire#3]
While useful for web users, the pop-up is useless for localhost users (because you cannot register the URL with either Dropbox or Gdocs). Not being able to close it means the settings are unavailable for such users.

**Comment by iLiviu** [comment]
Localhost worked fine on port 4200 (the default development port) for some of the URLS if you used the default API keys for Dropbox and Google Drive, as long as you used HTTPS. I whitelisted the other URLs that weren't added for localhost and also whitelisted default HTTPS port URLs on localhost.

As for that popup, yes, it may hide "Settings" on really small screens. I will add a close button when not connected.
