### ISSUE TITLE
Mutual Fund quotes support from Yahoo Finance

### ISSUE THREAD

**Issue by ashutoshsaboo** [iLiviu/road-to-fire#34]
Hi @iLiviu , Thanks for the great work with this portfolio tracker! :) 

I noticed mutual fund quotes aren't available from YFinance - https://github.com/iLiviu/asset-quote-service/blob/master/src/controllers/yfinance-quote-provider.ts#L150 , any reason on why this was disabled? I have seen YFinance to also provide fund quotes data correctly, here is the mutual fund screener for both NASDAQ and BSE exchange - https://finance.yahoo.com/screener/unsaved/ec5ee46f-1df1-48e1-bbf0-167c61bb80d3 . 

I think these mutual fund quotes are fetched very similarly to stock quotes, i.e, based on ticker code rather than ISIN. Here based on the same [url schema as here](https://github.com/iLiviu/asset-quote-service/blob/master/src/controllers/yfinance-quote-provider.ts#L114), I was able to request quotes for a fund from BSE exhange (Indian mutual fund) as well as Vanguard fund (from NASDAQ) simultaneously - https://query1.finance.yahoo.com/v7/finance/quote?lang=en-US&region=US&corsDomain=finance.yahoo.com&symbols=0P0000XVTL.BO,VSTSX . 

One hack to add these funds is by putting them under the 'stocks' category on [road-to-fire app](https://roadtofire.iliviu.me/). However, it'd be much better, as well as allow for better/granular asset allocation graphs on the portfolio tracker if we can support for mutual fund quotes the same way (i.e, by providing ticker rather than ISIN). Can we start supporting these too for the same reasons mentioned above?

PS: The only mutual fund quote screener i found in the backend quotes api was via FT - https://github.com/iLiviu/asset-quote-service/blob/00b0bacc286ff252ccf1a49ab6badd43b9c1ce01/src/controllers/ft-quote-provider.ts#L55 - which has far lesser fund ticker quotes data than YFinance (for example for BSE/NSE exchange funds).

**Comment by iLiviu** [comment]
I changed the asset quote service to get quotes for mutual funds that are provided by short symbol using yahoo finance. When you add a mutual fund asset, do not provide the exchange code, just the short symbol for the fund, otherwise you will get an error. 
But please note that mutual funds are not treated separately in graphs. The are categorized according to what assests they own (stocks, bonds, etc).
