### ISSUE TITLE
Lost all data 

### ISSUE THREAD

**Issue by valentinbadea** [iLiviu/road-to-fire#52]
I didn't have the data backed up online. I use only local storage. Today, something happened, and I lost progress.
I assume it is somewhere in Chrome, as I have 6 MB of data. How can I restore it?

**Comment by iLiviu** [comment]
The 6 MB may be just cache storage only. Unfortunately, the browser may decide to clear the app's data in certain scenarios (you didn't install it as an app, you are running low on device storage, etc). This is why using cloud sync is recommended.
