### ISSUE TITLE
Sync permissions are too wide

### ISSUE THREAD

**Issue by tokou** [iLiviu/road-to-fire#7]
Syncing with Google Drive and Dropbox require permissions that are too wide

Google Drive: "See, edit, create, and delete all of your Google Drive files"
Dropbox: "Full Dropbox: This app has full read/write access to any file inside the user's Dropbox"

It would be nice if only a folder was targeted

**Comment by iLiviu** [comment]
Unfortunately neither Google nor Dropbox allow an app to have access to one user folder only. It allows an app to gain access to a private app folder only, however the design of the app storage is to make it shareable by other apps (for example a budget tracker that would use the same data), and this wouldn't be possible if the folder was private to this app only.
