### ISSUE TITLE
Suggestion: Add asset tracking

### ISSUE THREAD

**Issue by azthec** [iLiviu/road-to-fire#8]
Hello, it would be cool if the current value of stocks would be updated through an API, even if at a low rate such as once per day! Asking for the ISIN on the same menu you get the asset ticker and title would make this realistic. https://stackoverflow.com/a/10040996

I don't think checking a third party for the valuation of some asset would be a great privacy concern, but if so you can always make it optional.

**Comment by iLiviu** [comment]
The app already gets the quotes automatically as long as you provide the exchange where the stock is traded and the symbol (ticker) of the stock. You can also get the quote by entering the ISIN in the symbol field, and leaving the exchange field blank, however this mode works with less stocks.
