### ISSUE TITLE
Mobile Shortcut as app has oauth problems

### ISSUE THREAD

**Issue by valentinbadea** [iLiviu/road-to-fire#9]
It will be nice if there will be support to have tha page as an app. Chrome has this ability but after I create the shortcut on main screen the oauth is lost(guessing)

> 400. That’s an error.

Error: redirect_uri_mismatch

The redirect URI in the request, https://roadtofire.iliviu.me/portfolio/home?utm_source=homescreen, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/801129580490-kbquipjice5v26b5jtpmhnncs31li7pv.apps.googleusercontent.com?project=801129580490

Learn more

Request Details
redirect_uri=https://roadtofire.iliviu.me/portfolio/home?utm_source=homescreen
scope=https://www.googleapis.com/auth/drive
client_id=801129580490-kbquipjice5v26b5jtpmhnncs31li7pv.apps.googleusercontent.com
response_type=token
That’s all we know.

**Comment by iLiviu** [comment]
Google requires whitelisting each exact URL from where the authentication is requested. I added this one and it should work fine now.
